package com;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

	@DynamoDBTable(tableName = "userposttable")
	public class UserPostModel {
	 
		private String userno;
		private String posttitle;
		private String postcontext;
		private String postid;
		private int numSpread;
		private int numSpams;
		
		@DynamoDBAutoGeneratedKey
		@DynamoDBHashKey(attributeName = "postid")
		public String getPostid() {
			return postid;
		}

		public void setPostid(String postid) {
			this.postid = postid;
		}
		
		@DynamoDBIndexHashKey(globalSecondaryIndexName="userno-index", attributeName="userno")
		public String getUserno() {
			return userno;
		}

		public void setUserno(String userno) {
			this.userno = userno;
		}
		
		@DynamoDBAttribute(attributeName = "posttitle")
		public String getPosttitle() {
			return posttitle;
		}

		public void setPosttitle(String posttitle) {
			this.posttitle = posttitle;
		}
		
		@DynamoDBAttribute(attributeName = "postcontext")
		public String getPostcontext() {
			return postcontext;
		}

		public void setPostcontext(String postcontext) {
			this.postcontext = postcontext;
		}
		
		@DynamoDBAttribute(attributeName = "numspread")
		public int getNumSpread() {
			return numSpread;
		}

		public void setNumSpread(int numSpread) {
			this.numSpread = numSpread;
		}
		
		@DynamoDBAttribute(attributeName = "numspams")
		public int getNumSpams()
		{
			return this.numSpams;
		}
		
		public void setNumSpams(int numSpams)
		{
			this.numSpams = numSpams;
		}
	}
	